apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kb8p3iv18-python 
  janus-idp.io/tekton: kb8p3iv18-python
  backstage.io/kubernetes-id: kb8p3iv18-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kb8p3iv18-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  