apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kb8p3iv18-python-gitops
  description: This is GitOps manifest for kb8p3iv18-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kb8p3iv18-python
    backstage.io/kubernetes-id: kb8p3iv18-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kb8p3iv18-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kb8p3iv18-python
