apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kb8p3iv18-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kb8p3iv18-python 
  name: kb8p3iv18-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kb8p3iv18-python 
